version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "sunday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "greirson"
    commit-message:
      prefix: "deps"
      include: "scope"
    groups:
      typescript:
        patterns:
          - "typescript"
          - "@types/*"
          - "ts-*"
      testing:
        patterns:
          - "jest"
          - "@types/jest"
          - "ts-jest"
      linting:
        patterns:
          - "eslint*"
          - "@typescript-eslint/*"
          - "prettier"